CC = gcc
CXX = g++

CFLAGS = -Wall $(INCLUDES)
CPPFLAGS = -Wall $(INCLUDES)

FFTW_INCLUDE = -I/opt/astro/SL53/include
FITS_INCLUDE = 
GSL_INCLUDE = 
OPENCV_INCLUDE = -I/direct/astro+u/apetri/misc

INCLUDES = -I../include $(FFTW_INCLUDE) $(FITS_INCLUDE) $(GSL_INCLUDE) $(OPENCV_INCLUDE)