CC = mpicc
PYTHON = python

CFLAGS = -g -Wall $(INCLUDES)
LDFLAGS = -g
LDLIBS = $(LINK)

INCLUDES = $(FITSINC) -I../include
LINK = $(FITSLINK) -L../lib -lconvergence

#Point to your cfitsio installation
FITSINC = -I/opt/astro/SL64/include
FITSLINK = -L/opt/astro/SL64/lib -lcfitsio