/* DO NOT EDIT THIS FILE - IT IS GENERATED FROM build_options.py. Edit that. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "options.h"

int handler(void *user,const char *section,const char *name, const char *value){
		
		sys_options *options = (sys_options*) user;
		
		#define MATCH(s,n) strcmp(section,s)==0 && strcmp(name,n)==0

 
		if(0){
		} else if(MATCH("maps","root_name")){
				options->root_name = strdup(value);
				} else if(MATCH("maps","num_realizations")){
				options->num_realizations = atoi(value);
				} else{
		return 0;
		}
		return 1;
}

void print_options(sys_options *options){
    printf("\n[maps]\n\n");
    printf("root_name = %s\n",options->root_name);
    printf("num_realizations = %d\n",options->num_realizations);
}