/* DO NOT EDIT THIS FILE - IT IS GENERATED FROM build_options.py. Edit that. */

#ifndef __OPTIONS_H
#define __OPTIONS_H

typedef struct{
		
char* root_name;
int num_realizations;

} sys_options;

int handler(void *,const char*,const char*,const char*);
void print_options(sys_options *options);

#endif
		
